#!/usr/bin/env python3

import sys
from parser import parse_equation

def main():

	if len(sys.argv) != 2:
		print("❗️ Program expects input in this format: ./computor \"equation\"")
		sys.exit(1)

	try:
		side_polys = parse_equation(sys.argv[1])
		for poly in side_polys:
			print(poly)
	except ValueError as e:
		print(f"Error: {e}", file=sys.stderr)
		sys.exit(1)
	

# my guard to say "Only run this when this file is the program entry point.”
# this way I avoid accidental execution if i ever do import computor in another file
if __name__ == "__main__":
	main()