#!/usr/bin/env python3

import sys
from parser import parse_equation
from reducer import reduce_polynomial, format_reduced_form
from solver import solve_polynomial
from utils import *

def main():

	if len(sys.argv) != 2:
		print("❗️ Program expects input in this format: ./computor \"equation\"")
		sys.exit(1)

	try:
		left_dict, right_dict = parse_equation(sys.argv[1])
		reduced_dict = reduce_polynomial(left_dict, right_dict)
		print(color(f"Reduced form: {format_reduced_form(reduced_dict)}", YELLOW))
		solve_polynomial(reduced_dict) # solver prints degree + solutions/messages
	except ValueError as e:
		print(color(f"❗️ Error: {e}", RED), file=sys.stderr)
		sys.exit(1)

# my guard to say "Only run this when this file is the program entry point.”
# this way I avoid accidental execution if i ever do import computor in another file
if __name__ == "__main__":
	main()